---
- name: Ensure root .ssh exists
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Fetch GitHub keys
  uri:
    url: "https://github.com/{{ item }}.keys"
    return_content: yes
  register: ssh_keys
  loop: "{{ github_ssh_users }}"

- name: Install SSH keys
  authorized_key:
    user: root
    key: "{{ item.1 }}"
    state: present
  loop: "{{ ssh_keys.results | subelements('content_lines') }}"
